### ISSUE TITLE
Re-Arrange Directory Structure

### ISSUE THREAD

**Issue by clundin25** [googleapis/enterprise-certificate-proxy#60]
The signer clients should be lifted out of the internal folder and made public. The utils they depend on should remain internal.

**Comment by clundin25** [comment]
Something like this should work:

```
➜ tree
.
├── client
├── cshared
├── internal
│   └── utils
└── signers
    ├── darwin
    ├── linux
    └── windows
```

**Comment by cds2-stripe** [comment]
Hey @clundin25 ! I was about to submit this as a feature request and found this. We'd really like to use your signer implementations if you wouldn't mind making them public.

Thank you!

**Comment by clundin25** [comment]
Thanks for your comment @cds2-stripe ! We will work on this soon, I will post any updates here!

**Comment by andyrzhao** [comment]
Hi @cds2-stripe, thanks for your interest in using our signer implementations. Can you provide a bit more context on what you are trying to accomplish to make sure everyone is on the same page? For example, are you trying to take a direct dependency on "ncrypt.go" and why? Our current design intentionally hides the signer details (which is very OS-specific) - instead, we provide a unified, OS-agnostic entry-point with client.go. The internal implementation is also not polished and subject to change, so we want to avoid exposing it to the public as a matter of principle.

**Comment by cds2-stripe** [comment]
Hey @andyrzhao,

I was looking for an up to date, maintained implementation of a macOS keychain API in Go. 

Specifically, I wanted something to read certificates from the keychain which exposed an implementation of `crypto.Signer` to build a `tls.Certificate`. Internally we have authenticating reverse proxies requiring mutual TLS.

I briefly looked at `client.go`, but that seemed to require more Google EAP specific configuration. Do you still suggest using the OS-agnostic client?

**Comment by andyrzhao** [comment]
Gotcha. In that case, I recommend you try out the OS-agnostic client.go first - there is nothing "Google-specific" about the setup and JSON configurations that we defined. As an example, you can see how our Golang API library integrates with the client: https://github.com/googleapis/google-api-go-client/blob/main/transport/cert/enterprise_cert.go
You just need to make sure to install the ecp binary onto your device, either downloading our precompiled notarized binaries (uploaded in Assets), or you can compile your own.

Long term, the right thing to do may be to move out the OS-specific signer implementations into their own Github repos, so folks can import them directly as github go modules - if we make the signer stack public in this repo, then we end up polluting the go mod dependency tree for those depending on our client (ex. we would run into compilation issues since the windows stack can only be compiled on windows.)

**Comment by cds2-stripe** [comment]
Got it - thank you. Ideally we wouldn't have to bundle the ECP binary just to get access to a `crypto.Signer` interface, and we also don't need any of the RPC mechanisms. We're just building a custom `tls.Config` to pass to a reverse proxy daemon we use to expose mTLS protected internal applications to CLI apps running on macbooks.

I'll wait and see if the signer implementations get moved out to a place we can import them directly as Go modules.

Thanks for engaging - this looks like a really cool project!

**Comment by andyrzhao** [comment]
We created a public wrapper API for darwin & keychain in https://github.com/googleapis/enterprise-certificate-proxy/pull/80. Consider this an experimental client. We will do the same for other OSes if this works well.

**Comment by cds2-stripe** [comment]
Thank you so much!

**Comment by andyrzhao** [comment]
Created linux and windows public clients as well in https://github.com/googleapis/enterprise-certificate-proxy/pull/81 and https://github.com/googleapis/enterprise-certificate-proxy/pull/83. Will publish as v0.2.5
